// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var PixiDraw = require("../utils/pixiDraw");

function pixiDraw(prim) {
  PixiDraw.default(prim);
  return /* () */0;
}

function update(state) {
  PixiDraw.default(state);
  return /* () */0;
}

exports.pixiDraw = pixiDraw;
exports.update = update;
/* ../utils/pixiDraw Not a pure module */
