// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");
var Vector$Whatever = require("../utils/Vector.bs.js");
var PixiDraw = require("../utils/pixiDraw");

function pixiDraw(prim) {
  PixiDraw.default(prim);
  return /* () */0;
}

function update(state) {
  var prim = Belt_List.reduce(state[/* entity */0], /* [] */0, (function (images, entity) {
          var image = Belt_MapString.get(state[/* image */2], entity);
          if (image !== undefined) {
            return Belt_List.add(images, /* record */[
                        /* entity */entity,
                        /* position */Belt_MapString.getWithDefault(state[/* position */1], entity, Vector$Whatever.create(0.0, 0.0))
                      ]);
          } else {
            return images;
          }
        }));
  PixiDraw.default(prim);
  return /* () */0;
}

exports.pixiDraw = pixiDraw;
exports.update = update;
/* ../utils/pixiDraw Not a pure module */
