// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Vector$Whatever = require("../util/Vector.bs.js");

var IO = { };

var io = /* record */[
  /* mouseButtons */-1,
  /* mousePosition */Vector$Whatever.create(0.0, 0.0)
];

var match = document.querySelector("body");

if (!(match == null)) {
  match.addEventListener("mousemove", (function (e) {
          io[/* mouseButtons */0] = e.buttons;
          io[/* mousePosition */1] = Vector$Whatever.create(e.x, e.y);
          return /* () */0;
        }));
}

var disableContextMenu = (
  function() { 
    document.addEventListener("contextmenu", e => {
      e.preventDefault();
    });
  }
);

function update(param) {
  return io;
}

exports.IO = IO;
exports.io = io;
exports.disableContextMenu = disableContextMenu;
exports.update = update;
/* io Not a pure module */
