// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function update(state) {
  return Belt_List.reduce(state[/* entity */0], state, (function (newState, entity) {
                return newState;
              }));
}

exports.update = update;
/* No side effect */
