// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function update(state) {
  var last = state[/* timeNow */3];
  var now = performance.now();
  return /* record */[
          /* entity */state[/* entity */0],
          /* position */state[/* position */1],
          /* image */state[/* image */2],
          /* timeNow */now,
          /* delta */(now - last) / 1000.0
        ];
}

exports.update = update;
/* No side effect */
