// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var V4 = require("uuid/v4");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");
var Vector$Whatever = require("../util/Vector.bs.js");
var Image_Component$Whatever = require("../component/Image_Component.bs.js");

var humanImage = (require('./assets/human.png').default);

function create(state) {
  var entity = V4();
  return /* record */[
          /* entity : :: */[
            entity,
            state[/* entity */0]
          ],
          /* position */Belt_MapString.set(state[/* position */1], entity, Vector$Whatever.create(0.0, 1.0)),
          /* image */Belt_MapString.set(state[/* image */2], entity, Image_Component$Whatever.create(humanImage)),
          /* timeNow */state[/* timeNow */3],
          /* delta */state[/* delta */4]
        ];
}

exports.humanImage = humanImage;
exports.create = create;
/* humanImage Not a pure module */
