// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Position = 0;

var $$Image = 0;

var Transform = 0;

exports.Position = Position;
exports.$$Image = $$Image;
exports.Transform = Transform;
/* No side effect */
