// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function create(src, position) {
  return /* record */[
          /* src */src,
          /* position */position
        ];
}

exports.create = create;
/* No side effect */
