// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function create(translation, rotation, scale) {
  return /* record */[
          /* translation */translation,
          /* rotation */rotation,
          /* scale */scale
        ];
}

exports.create = create;
/* No side effect */
