// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Draw_System$Whatever = require("./system/Draw_System.bs.js");
var Position_Component$Whatever = require("./component/Position_Component.bs.js");

var initialState = /* record */[
  /* entity : :: */[
    1,
    /* [] */0
  ],
  /* position : :: */[
    2,
    /* [] */0
  ]
];

var dd = Position_Component$Whatever.create(/* () */0);

function logic(state) {
  Draw_System$Whatever.update(state);
  requestAnimationFrame((function (param) {
          return logic(state);
        }));
  return /* () */0;
}

logic(initialState);

exports.initialState = initialState;
exports.dd = dd;
exports.logic = logic;
/* dd Not a pure module */
