// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");
var Vector$Whatever = require("./utils/Vector.bs.js");
var Draw_System$Whatever = require("./system/Draw_System.bs.js");
var Move_System$Whatever = require("./system/Move_System.bs.js");
var Image_Component$Whatever = require("./component/Image_Component.bs.js");
var Position_Component$Whatever = require("./component/Position_Component.bs.js");

var initialState = /* record */[
  /* entity : [] */0,
  /* position */Belt_MapString.empty,
  /* image */Belt_MapString.empty
];

var dd = Position_Component$Whatever.create(0.0, 0.0);

var entity = "xD";

function logic(state) {
  var newState = Belt_List.reduce(state[/* entity */0], state, (function (newState, entity) {
          return Move_System$Whatever.update(entity, state);
        }));
  Draw_System$Whatever.update(newState);
  requestAnimationFrame((function (param) {
          return logic(newState);
        }));
  return /* () */0;
}

logic(/* record */[
      /* entity : [] */0,
      /* position */Belt_MapString.set(Belt_MapString.empty, entity, Vector$Whatever.create(0.0, 1.0)),
      /* image */Belt_MapString.set(Belt_MapString.empty, entity, Image_Component$Whatever.create("human.png"))
    ]);

exports.initialState = initialState;
exports.dd = dd;
exports.entity = entity;
exports.logic = logic;
/* dd Not a pure module */
